trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      pip install pandas numpy
    displayName: 'Install Python dependencies'

  - script: |
      python etl_pipeline.py
    displayName: 'Run ETL Script'
